version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: circleci/node:12.16.1
jobs:
    test:
        <<: *defaults
        steps:
            - checkout

            - run:
                  name: Install and build package
                  command: yarn install --frozen-lockfile

            - run:
                  name: Run tests
                  command: yarn test --runInBand --no-cache --coverage

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
workflows:
    version: 2
    build_test:
        jobs:
            - test
