version: 2
jobs:
    build:
        docker:
            - image: circleci/node:12.16.1

        working_directory: ~/repo

        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
                      - v1-dependencies-

            - run:
                  name: Install and build package
                  command: yarn install --frozen-lockfile

            - run:
                  name: Run tests
                  command: yarn test --runInBand --no-cache --coverage

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}
